### ISSUE TITLE
ImportError: cannot import name 'LOADERS' from 'simpleconf'

### ISSUE THREAD

**Issue by miguellarraz** [pwwang/vcfstats#24]
Hi, I am trying to run the following command from the README: 
`vcfstats --vcf test_datasets/test.vcf \
	--outdir out/ \
	--formula 'COUNT(1) ~ CONTIG' \
	--title 'Number of variants on each chromosome' \
	--config out/config.toml`

and I get the following error, with traceback:
```
Traceback (most recent call last):
  File "/Users/xxx/opt/anaconda3/envs/dis/bin/vcfstats", line 5, in <module>
    from vcfstats.cli import main
  File "/Users/xxx/opt/anaconda3/envs/dis/lib/python3.7/site-packages/vcfstats/__init__.py", line 4, in <module>
    from . import macros
  File "/Users/xxx/opt/anaconda3/envs/dis/lib/python3.7/site-packages/vcfstats/macros.py", line 5, in <module>
    from .utils import MACROS
  File "/Users/xxx/opt/anaconda3/envs/dis/lib/python3.7/site-packages/vcfstats/utils.py", line 9, in <module>
    from pyparam import defaults
  File "/Users/xxx/opt/anaconda3/envs/dis/lib/python3.7/site-packages/pyparam/__init__.py", line 5, in <module>
    from .params import Params
  File "/Users/xxx/opt/anaconda3/envs/dis/lib/python3.7/site-packages/pyparam/params.py", line 9, in <module>
    from simpleconf import LOADERS, Config
ImportError: cannot import name 'LOADERS' from 'simpleconf' (/Users/xxx/opt/anaconda3/envs/dis/lib/python3.7/site-packages/simpleconf/__init__.py)
```

I have installed vcfstats using pip. 

Many thanks,
Miguel

**Comment by tuannguyen8390** [comment]
Hello there, I encounter the same problem, how did you fix it @miguellarraz ?

**Comment by pwwang** [comment]
Sorry for the late response. 

@tuannguyen8390 
Does `pip install -U vcfstats` fix it for you?
