### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by mbaddoo** [pwwang/vcfstats#7]
Hello! Thanks for this great tool.  I used pip to install but when I ran 
vcfstats --vcf examples/sample.vcf \
	--outdir examples/ \
	--formula 'COUNT(1) ~ CONTIG' \
	--title 'Number of variants on each chromosome' \
	--config examples/config.toml
I was met with the following error:
Traceback (most recent call last):
  File "/Users/mothership/miniconda3/bin/vcfstats", line 5, in <module>
    from vcfstats import main
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/vcfstats/__init__.py", line 9, in <module>
    from cyvcf2 import VCF
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "cyvcf2/cyvcf2.pyx", line 1, in init cyvcf2.cyvcf2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

Might you be able to advise me on what I have done wrong? 

Many thanks!
Melody

**Comment by mbaddoo** [comment]
Hello again-
Hmmm...I may have fixed the issue I commented about above by uninstalling and re-installing numpy.  Now when I run the command with sample.vcf I am met with a new error:

vcfstats --vcf examples/sample.vcf --outdir ./ --formula 'COUNT(1) ~ CONDIG' --title 'Number of variants on each chromosome' --config examples/config.toml
[2021-08-04 16:45:20,940 DEBUG] Parsing ['--vcf', 'examples/sample.vcf', '--outdir', './', '--formula', 'COUNT(1) ~ CONDIG', '--title', 'Number of variants on each chromosome', '--config', 'examples/config.toml']
[2021-08-04 16:45:20,941 DEBUG] - Parsing item '--vcf'
[2021-08-04 16:45:20,941 DEBUG]   Previous: None
[2021-08-04 16:45:20,941 DEBUG]   Matched: <ParamPath(-v, --vcf :: path) @ 140716686842704>, name=vcf, type=None, value=None
[2021-08-04 16:45:20,941 DEBUG] - Parsing item 'examples/sample.vcf'
[2021-08-04 16:45:20,941 DEBUG]   Previous: <ParamPath(-v, --vcf :: path) @ 140716686842704>
[2021-08-04 16:45:20,941 DEBUG]   Matched: None, name=None, type=None, value='examples/sample.vcf'
[2021-08-04 16:45:20,941 DEBUG]   Param '-v, --vcf' consumes 'examples/sample.vcf'
[2021-08-04 16:45:20,941 DEBUG] - Parsing item '--outdir'
[2021-08-04 16:45:20,941 DEBUG]   Previous: <ParamPath(-v, --vcf :: path) @ 140716686842704>
[2021-08-04 16:45:20,941 DEBUG]   Matched: <ParamAuto(-o, --outdir :: auto) @ 140716686843088>, name=outdir, type=None, value=None
[2021-08-04 16:45:20,941 DEBUG]   Closing previous argument
[2021-08-04 16:45:20,941 DEBUG] - Parsing item './'
[2021-08-04 16:45:20,941 DEBUG]   Previous: <ParamAuto(-o, --outdir :: auto) @ 140716686843088>
[2021-08-04 16:45:20,942 DEBUG]   Matched: None, name=None, type=None, value='./'
[2021-08-04 16:45:20,942 DEBUG]   Param '-o, --outdir' consumes './'
[2021-08-04 16:45:20,942 DEBUG] - Parsing item '--formula'
[2021-08-04 16:45:20,942 DEBUG]   Previous: <ParamAuto(-o, --outdir :: auto) @ 140716686843088>
[2021-08-04 16:45:20,942 DEBUG]   Matched: <ParamList(-f, --formula :: list) @ 140716686981712>, name=formula, type=None, value=None
[2021-08-04 16:45:20,942 DEBUG]   Closing previous argument
[2021-08-04 16:45:20,942 DEBUG] - Parsing item 'COUNT(1) ~ CONDIG'
[2021-08-04 16:45:20,942 DEBUG]   Previous: <ParamList(-f, --formula :: list) @ 140716686981712>
[2021-08-04 16:45:20,942 DEBUG]   Matched: None, name=None, type=None, value='COUNT(1) ~ CONDIG'
[2021-08-04 16:45:20,942 DEBUG]   Param '-f, --formula' consumes 'COUNT(1) ~ CONDIG'
[2021-08-04 16:45:20,942 DEBUG] - Parsing item '--title'
[2021-08-04 16:45:20,942 DEBUG]   Previous: <ParamList(-f, --formula :: list) @ 140716686981712>
[2021-08-04 16:45:20,942 DEBUG]   Matched: <ParamList(--title :: list) @ 140716686981392>, name=title, type=None, value=None
[2021-08-04 16:45:20,942 DEBUG]   Closing previous argument
[2021-08-04 16:45:20,942 DEBUG] - Parsing item 'Number of variants on each chromosome'
[2021-08-04 16:45:20,942 DEBUG]   Previous: <ParamList(--title :: list) @ 140716686981392>
[2021-08-04 16:45:20,942 DEBUG]   Matched: None, name=None, type=None, value='Number of variants on each chromosome'
[2021-08-04 16:45:20,943 DEBUG]   Param '--title' consumes 'Number of variants on each chromosome'
[2021-08-04 16:45:20,943 DEBUG] - Parsing item '--config'
[2021-08-04 16:45:20,943 DEBUG]   Previous: <ParamList(--title :: list) @ 140716686981392>
[2021-08-04 16:45:20,943 DEBUG]   Matched: <ParamAuto(-c, --config :: auto) @ 140716686981904>, name=config, type=None, value=None
[2021-08-04 16:45:20,943 DEBUG]   Closing previous argument
[2021-08-04 16:45:20,943 DEBUG] - Parsing item 'examples/config.toml'
[2021-08-04 16:45:20,943 DEBUG]   Previous: <ParamAuto(-c, --config :: auto) @ 140716686981904>
[2021-08-04 16:45:20,943 DEBUG]   Matched: None, name=None, type=None, value='examples/config.toml'
[2021-08-04 16:45:20,943 DEBUG]   Param '-c, --config' consumes 'examples/config.toml'
[2021-08-04 16:45:20,943 DEBUG]   Closing final argument: '-c, --config'
Traceback (most recent call last):
  File "/Users/mothership/miniconda3/bin/vcfstats", line 8, in <module>
    sys.exit(main())
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/vcfstats/__init__.py", line 167, in main
    load_config(opts['config'], opts)
  File "/Users/mothership/miniconda3/lib/python3.7/site-packages/vcfstats/__init__.py", line 120, in load_config
    raise OSError("Config file does not exist: {}".format(config))
OSError: Config file does not exist: examples/config.toml

Where can I find (or generate) the config.toml file?

Thanks!
Melody

**Comment by pwwang** [comment]
You can find one here:

https://github.com/pwwang/vcfstats/tree/master/examples

**Comment by mbaddoo** [comment]
Great!  Thank you very much!
Best-
Melody
